### ISSUE TITLE
upgrade dicom dependency

### ISSUE THREAD

**Issue by joeblew99** [andydotxyz/dicomgraphics#3]
Now here:

https://github.com/suyashkumar/dicom

Its about a year ahead of the current dependency.

**Comment by andydotxyz** [comment]
Hmm, unfortunately it's not API compatible so it would be a bit of work to move to that one - are there features added or some underlying reason to make the move?

**Comment by joeblew99** [comment]
no reason. Just me because i am currently building a medical system for a cardiologist.
I guess i should do this myself and let you know how it goes ?

**Comment by andydotxyz** [comment]
Updated in the new project: [dicomgraphics](/fynelabs/dicomgraphics)
